const trainingData = [
    { input: { good: 1, fantastic: 1, great: 1 }, output: { positive: 1 } },
    { input: { excellent: 1, great: 1 }, output: { positive: 1 } },
    { input: { amazing: 1, wonderful: 1 }, output: { positive: 1 } },
    { input: { happy: 1, joy: 1 }, output: { positive: 1 } },
    { input: { love: 1, liked: 1 }, output: { positive: 1 } },
    { input: { bad: 1, awful: 1 }, output: { negative: 1 } },
    { input: { terrible: 1, horrible: 1 }, output: { negative: 1 } },
    { input: { poor: 1, disappointing: 1 }, output: { negative: 1 } },
    { input: { sad: 1, unhappy: 1 }, output: { negative: 1 } },
    { input: { hate: 1, disliked: 1 }, output: { negative: 1 } },
    { input: { pleasure: 1, favorite: 1 }, output: { positive: 1 } },
    { input: { nice: 1, best: 1 }, output: { positive: 1 } },
    { input: { awesome: 1, joyful: 1 }, output: { positive: 1 } },
    { input: { fortunate: 1, sweet: 1 }, output: { positive: 1 } },
    { input: { success: 1, win: 1 }, output: { positive: 1 } },
    { input: { fail: 1, loss: 1 }, output: { negative: 1 } },
    { input: { dread: 1, fear: 1 }, output: { negative: 1 } },
    { input: { ugly: 1, terrible: 1 }, output: { negative: 1 } },
    { input: { nasty: 1, cruel: 1 }, output: { negative: 1 } },
    { input: { miserable: 1, unfortunate: 1 }, output: { negative: 1 } },
    { input: { suck: 1, terrible: 1 }, output: { negative: 1 } },
    { input: { sucks: 1, disgusting: 1 }, output: { negative: 1 } },
    { input: { cool: 1, awesome: 1 }, output: { positive: 1 } },
    { input: { worst: 1, bad: 1 }, output: { negative: 1 } },
    { input: { best: 1, good: 1 }, output: { positive: 1 } },
    { input: { positive: 1, enjoyable: 1 }, output: { positive: 1 } },
    { input: { negative: 1, boring: 1 }, output: { negative: 1 } },
];

module.exports = trainingData;